---
- hosts: runs_system_app
  gather_facts: no
  remote_user: pi
  vars:
    server_ip: "192.168.1.128"
    app: "ambient_temperature"

  tasks:
    - name: Create app directory
      file:
        path: "/home/pi/apps/{{ app }}"
        state: directory

    - name: Copy app
      notify:
        - restart app
      copy:
        src: "./src/"
        dest: "/home/pi/apps/{{ app }}/"

    - name: Install apt python dependencies
      become: yes
      apt:
        update_cache: yes
        name:
          # - "python3-pip"
          # - "python3-setuptools"
          # - "python3-systemd"
          # - "gpiod"

    - name: Install python dependencies
      pip:
        requirements: "/home/pi/apps/{{ app }}/requirements.txt"

    - name: Create systemd unit directory
      file:
        path: "/home/pi/.config/systemd/user"
        state: directory

    - name: Create systemd unit file
      template:
        src: "../templates/systemd.service"
        dest: "/home/pi/.config/systemd/user/{{ app }}.service"

    - name: Run service
      systemd:
        state: started
        daemon_reload: yes
        scope: user
        name: "{{ app }}"

    - name: Enable service
      systemd:
        enabled: yes
        scope: user
        name: "{{ app }}"

  handlers:
    - name: restart app
      systemd:
        state: restarted
        scope: user
        name: "{{ app }}"
