---
- hosts: all
  vars:
    - pi_password: "raspberry"
  gather_facts: no
  remote_user: pi
  become: true

  tasks:
    - name: Add pi user to the sudoers
      copy:
        dest: "/etc/sudoers.d/pi"
        content: "pi ALL=(ALL) NOPASSWD: ALL"
        mode: 0440

    - name: Add SSH Key
      get_url:
        url: https://github.com/dan1elhughes.keys
        dest: /home/pi/.ssh/authorized_keys
        mode: 0644

    - name: Disable password-only SSH
      notify:
        - restart ssh
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
        backup: yes

    - name: Disable root SSH
      notify:
        - restart ssh
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted
