---
- hosts: requires_python
  gather_facts: no
  remote_user: pi
  become: true

  tasks:
    - name: Install apt python dependencies
      apt:
        update_cache: yes
        name:
          - "python3-pip"
          - "python3-setuptools"
          - "python3-systemd"
          - "gpiod"
